//
// Created by LSH on 2025. 7. 23..
//

#ifndef WXWIDGETS_CLION_PROJECT_CONFIG_H
#define WXWIDGETS_CLION_PROJECT_CONFIG_H

const int FRAME_HEIGHT = 500;
const int FRAME_WIDTH = 500;
const int CELL_HEIGHT = 10;
const int CELL_WIDTH = 10;
const int BOARD_HEIGHT = FRAME_HEIGHT / CELL_HEIGHT;
const int BOARD_WIDTH = FRAME_WIDTH / CELL_WIDTH;

#endif //WXWIDGETS_CLION_PROJECT_CONFIG_H
